# Pytorch Tensor Funtions
### Created by Yatin arora

An Introduction to Pytorch
PyTorch is an open source machine learning library based on the Torch library,used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.
Pytorch contains a datatype called as 'Tensor'(torch.Tensor) which is a special array. A Tensor is capable of storing both a scalar value and a multidimentional matrix with same data-type. A Tensor can be created from python Data types and can be converted back. In addition these tensors can be used to perform special inbuild functions and mathematical operation. Note: A Tensor is capable of storing matrices beyond 3D


## Functions we are going to discuss today are:-
- torch.squeeze(unsqueeze)
- torch.mul
- torch.arrange
- torch.linspace
- torch.mean

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.squeeze

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: (A \times 1 \times B \times C \times 1 \times D)(A×1×B×C×1×D) then the out tensor will be of shape: (A \times B \times C \times D)(A×B×C×D) .

When dim is given, a squeeze operation is done only in the given dimension. If input is of shape: (A \times 1 \times B)(A×1×B) , squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape (A \times B)(A×B) .

In [0]:
# Example 1 - working 
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [0]:
y=torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

as you can see when we squeeze the tensor x its output does not contain 1's

In [0]:
# Example 2 - working (unsqueeze)
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

this is an example of how to unsqueeze

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
y = torch.squeeze(x,5)

IndexError: ignored

the cell shows an error because there is no 1 present at 5th position

Closing comments about when to use this function

## Function 2 - torch.mul

Multiplies each element of the input input with the scalar other and returns a new resulting tensor.

 
If input is of type FloatTensor or DoubleTensor, other should be a real number, otherwise it should be an integer

In [0]:
# Example 1 - working
a= torch.randn(3)
a

tensor([ 0.7122, -0.9577,  1.4390])

In [0]:
torch.mul(a, 100)

tensor([ 71.2215, -95.7686, 143.9049])

all elements  of a are multiplied by 100

In [0]:
# Example 2 - working
a = torch.randn(4, 1) 
a

tensor([[-1.4563],
        [-1.0670],
        [-1.4176],
        [-0.5990]])

In [0]:
b = torch.randn(1, 4)
b

tensor([[-0.1693,  0.3994, -0.3098, -0.1606]])

In [0]:
torch.mul(a, b)

tensor([[ 0.2466, -0.5816,  0.4511,  0.2339],
        [ 0.1807, -0.4261,  0.3305,  0.1714],
        [ 0.2400, -0.5661,  0.4391,  0.2277],
        [ 0.1014, -0.2392,  0.1856,  0.0962]])

as you can see we can multiply 2 matrices as well.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.mul(a,b,2)

TypeError: ignored

we can not input three arguments in the function.


we should use this function only when we need to do scaller multiplication or in two matrices.

## Function 3 - torch.arrange

Returns a 1-D tensor of size end-start/step with values from the interval [start, end) taken with common difference step beginning from start.

In [0]:
# Example 1 - working
torch.arange(start=0,end=10,step=3)

tensor([0, 3, 6, 9])

We create a tensor using arange function where we give start to be 0 and end to be 10 wit step 3 . So the first value will be zero and later i+3,



In [0]:
# Example 2 - working
torch.arange(1,1.6,0.2)

tensor([1.0000, 1.2000, 1.4000, 1.6000])

We can also give it a float value and in return we get a list of tensors .

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange([1,2,3])

TypeError: ignored

We cannot pass list when creating a tensor using arange , it only accepts start , end and step



Use this function when you need a specific tensors values

## Function 4 - torch.linspace

Returns a one-dimensional tensor of steps equally spaced points between start and end.

The output tensor is 1-D of size steps.

In [0]:
# Example 1 - working
torch.linspace(10,1)

tensor([10.0000,  9.9091,  9.8182,  9.7273,  9.6364,  9.5455,  9.4545,  9.3636,
         9.2727,  9.1818,  9.0909,  9.0000,  8.9091,  8.8182,  8.7273,  8.6364,
         8.5455,  8.4545,  8.3636,  8.2727,  8.1818,  8.0909,  8.0000,  7.9091,
         7.8182,  7.7273,  7.6364,  7.5455,  7.4545,  7.3636,  7.2727,  7.1818,
         7.0909,  7.0000,  6.9091,  6.8182,  6.7273,  6.6364,  6.5455,  6.4545,
         6.3636,  6.2727,  6.1818,  6.0909,  6.0000,  5.9091,  5.8182,  5.7273,
         5.6364,  5.5455,  5.4545,  5.3636,  5.2727,  5.1818,  5.0909,  5.0000,
         4.9091,  4.8182,  4.7273,  4.6364,  4.5455,  4.4545,  4.3636,  4.2727,
         4.1818,  4.0909,  4.0000,  3.9091,  3.8182,  3.7273,  3.6364,  3.5455,
         3.4545,  3.3636,  3.2727,  3.1818,  3.0909,  3.0000,  2.9091,  2.8182,
         2.7273,  2.6364,  2.5455,  2.4545,  2.3636,  2.2727,  2.1818,  2.0909,
         2.0000,  1.9091,  1.8182,  1.7273,  1.6364,  1.5455,  1.4545,  1.3636,
         1.2727,  1.1818,  1.0909,  1.00

Create a random date start with 10 and end in 1

In [0]:
# Example 2 - working
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

From 1 to 10 get a 5 equally distributed datas

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(10)

TypeError: ignored

the function needs two arguments as input

We should use this function to get random data points with start and end as default params

## Function 5 - torch.mean

The torch.mean function returns the mean or average of your tensor.

In [0]:
# Example 1 - working
x = torch.randn(4)
print(x)
torch.mean(x)

tensor([-1.7821, -0.2879, -0.2051, -0.2975])


tensor(-0.6431)

We can see in this example the torch.mean function is applied to a tensor vector which is just adding all the numbers and dividing by the count.

In [0]:
# Example 2 - working
x = torch.randn((3,4))
print(x)
torch.mean(x, dim=0)

tensor([[ 1.1210,  1.1721, -1.4537, -0.1289],
        [ 1.0589, -1.1667, -0.2002, -1.2073],
        [-0.9118, -0.0111, -0.4785,  1.3947]])


tensor([ 0.4227, -0.0019, -0.7108,  0.0195])

We can see in this example the torch.mean function is applied to a (3, 4) matrix except the dim parameter is set to 0. This is specifying that we want the average over all rows (for each column). We can set dim to 1 if we want the average over all columns (for each row).

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([0,1,0,1,0],dtype=torch.bool)
torch.mean(x)

RuntimeError: ignored

In this example, our tensor x is a boolean data type which is a (0, 1) or (False, True) data type. Applying the mean function to this boolean tensor results in a RuntimeError because you cannot get the mean or average of boolean data types. That is why the RunetimeError says it can only calculate the mean of floating types.

This function should be used when you need to obtain the mean of your tensor, you can also specify which dimension to calculate the mean.



## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 5.9MB/s 


In [0]:
import jovian

In [0]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
